inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "db/**/*"

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "bin/**/*"

Style/StringLiterals:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false
