inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "db/**/*"
    - 'vendor/**/*'
    - 'lib/tasks/*'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "bin/**/*"

Style/StringLiterals:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
