version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.development
    stdin_open: true
    tty: true
    command: ./bin/start_dev_server
    volumes:
      - ".:/beacon"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:11.1"
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  bundle:
