version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.development
    stdin_open: true
    tty: true
    command: ./bin/start_dev_server
    volumes:
      - ".:/beacon"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: "postgres:11.1"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  resque:
    build:
      context: .
    command: bundle exec rake resque:work QUEUE='*'
    volumes:
      - .:/myapp
      - bundle:/bundle
    depends_on:
      - db
      - redis
volumes:
  bundle: {}
  redis: {}
