email:
  delivery_method: :smtp
  raise_delivery_errors: true
  perform_deliveries: true
  default_url_options:
    :host: localhost:3000
  smtp_settings:
    :address: localhost
    :port: 1025
    :authentication: plain
    :user_name: 
    :password:
