test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

heroku:
  service: Mirror
  primary: google
  mirrors:
    - local

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
google:
  service: GCS
  project: beacon
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>
  bucket: beacon-uploads
