encryption:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', "alongandunguessablekey") %>
throttling:
  max_abuse_reports_per_day: <%= ENV.fetch('MAX_ABUSE_REPORTS_PER_DAY', 5) %>
  max_general_contacts_per_day: <%= ENV.fetch('MAX_GENERAL_CONTACTS_PER_DAY', 2) %>
  max_issues_per_day: <%= ENV.fetch('MAX_ISSUES_PER_DAY', 3) %>
emails:
  robot: <%= ENV.fetch('ROBOT_EMAIL_ADDRESS', "donotreply@coc-beacon.com") %>
  support: <%= ENV.fetch('SUPPORT_EMAIL_ADDRESS', "support@coc-beacon.com") %>
  abuse: <%= ENV.fetch('ABUSE_EMAIL_ADDRESS', "abuse@coc-beacon.com") %>
sms:
  from: <%= ENV.fetch('TWILIO_PHONE_NUMBER', nil) %>
  account_sid: <%= ENV.fetch('TWILIO_ACCOUNT_SID', "") %>
  auth_token: <%= ENV.fetch('TWILIO_AUTH_TOKEN', "") %>
oauth:
  github_app_id: <%= ENV['GITHUB_APP_ID'] %>
  github_app_secret: <%= ENV['GITHUB_APP_SECRET'] %>
  gitlab_app_id: <%= ENV['GITLAB_APP_ID'] %>
  gitlab_app_secret: <%= ENV['GITLAB_APP_SECRET'] %>
google:
  analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
