common: &common
  log_all_models: true
  admin_user: false
  admin_user_login: false
  allocated_sku: false
  attribute_name: false
  attribute_value: false
  attribute_value_type: false
  brand: false
  buy_delivery: false
  buy_hizzy_allocation: false
  client: false
  client_color: false
  client_credit: false
  client_discount_program: false
  client_hizzy: false
  client_item_type_avoid: false
  client_item_type_group_avoid: false
  client_item_type_group_spendiness: false
  client_item_type_spendiness: false
  client_multi_attribute: false
  client_promo_code: false
  client_scalar_attributes: false
  client_status: false
  client_website: false
  color: false
  credit_spend: false
  discount_program: false
  gift: false
  gift_mailing: false
  hizzy: false
  instagram_post: false
  item: false
  item_exchange: false
  item_exchange_reservation: false
  item_status: false
  item_type: false
  item_type_group: false
  item_type_group_set: false
  merch_buy: false
  merch_date: false
  ordered_sku: false
  payment_log: false
  photo_asset: false
  promo_code: false
  promo_code_campaign: false
  purchase_order: false
  received_sku: false
  return_bag_size: false
  rma: false
  shipment: false
  shipment_item: false
  shipment_status: false
  shipment_stylist_assignment: false
  shipping_label: false
  size: false
  sku: true
  style: true
  style_multi_attribute: false
  style_scalar_attributes: false
  style_status: false
  style_variant: true
  team: false
  team_membership: false
  user: false
  usps_refund: false
  vendor: false
  vendor_delivery: false
  video_asset: false
  website: false

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
